# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

if __name__ == "__main__":
    ans = 0

    num_i = 1
    num_ip1 = 2
    hol_val = -1
    while num_ip1 < (4 * 10**6):
        hol_val = num_ip1
        num_ip1 += num_i
        num_i = hol_val

        if num_i % 2 == 0:
            ans += num_i
    print(ans)
#%%
